baseURL = "https://cindyisawesome.lawver.net"
languageCode = "en-us"
title = "Cindy Li Is Awesome and Everyone Loves Her"
theme = "ananke"
paginate = 15

[params]
  description = ""
  recent_posts_number=25
  custom_css = ["css/nav.css", "css/gallery.css", "css/header.css", "css/tag-list.css"]
  featured_image = "/photos/site/cindy_is_awesome.jpg"

[imaging]
quality=75
resize="800x"

[taxonomies]
tags = "tags"

[[menu.main]]
  name = "Browse the Tags"
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Share Your Cindy Story"
  identifer = "share"
  url = "/share"


# [related]
#   threshold = 80
#   includeNewer = true
#   toLower = true
#   [[related.indices]]
#   name = "date"
#   weight = 100
